use_debugger: True
output_dir: "/kaggle/working/"
thresholds: [0.3, 0.4, 0.5]
device: "cuda"


dataset:
  data: "/kaggle/input/shapenet"
  json_mapper: "/kaggle/working/3D-Reconstruction-GP/dataset mapper/ShapeNet.json"

model:
  pretrained: None  # either None, 1k or 22k
  convnext_version: b
  negative_slope: 0.2
  use_bias: False

optim:
  type: AdamW   # can be Adam or sgd?
  lr: 0.001
  

train:
  epochs: 10
  epochs_till_merger: 4
  batch_size: 4
  start_epoch: 0
  save_every: 3
  reduce_lr_epoch: 130
  reduce_lr_factor: 0.5
