use_debugger: True
output_dir: "/kaggle/working/"
thresholds: [0.2, 0.25, 0.3, 0.35, 0.4]
device: "cuda"


dataset:
  data: "/kaggle/input/shapenet"
  json_mapper: "/kaggle/working/Pix2VoxSharp/dataset mapper/ShapeNet.json"

model:
  pretrained: True  # either None, 1k or 22k
  convnext_version: b
  negative_slope: 0.2
  use_bias: False

optim:
  type: AdamW   # can be Adam or sgd?
  lr: 0.001
  

train:
  epochs: 150
  epochs_till_merger: 80
  batch_size: 50
  start_epoch: 0
  save_every: 3
  reduce_lr_epoch: 110
  reduce_lr_factor: 0.5
  continue_from_checkpoint: True
  checkpoint_id: 2025-03-21_21-35-59
  checkpoint_type: best
